// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntry, id)
	return err
}

const deleteEntryByListAndUser = `-- name: DeleteEntryByListAndUser :exec
DELETE FROM entries WHERE list_id = $1 AND user_id = $2
`

type DeleteEntryByListAndUserParams struct {
	ListID pgtype.UUID `json:"list_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteEntryByListAndUser(ctx context.Context, arg DeleteEntryByListAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteEntryByListAndUser, arg.ListID, arg.UserID)
	return err
}

const getRankedEntriesByDuration = `-- name: GetRankedEntriesByDuration :many
SELECT
  e.id, e.list_id, e.user_id, e.value_number, e.value_duration_ms, e.value_text, e.manual_rank, e.note, e.submitted_at, e.updated_at,
  u.display_name,
  u.avatar_url,
  ROW_NUMBER() OVER (ORDER BY e.value_duration_ms ASC NULLS LAST) AS rank
FROM entries e
JOIN users u ON u.id = e.user_id
WHERE e.list_id = $1
ORDER BY rank ASC
`

type GetRankedEntriesByDurationRow struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Rank            int64              `json:"rank"`
}

func (q *Queries) GetRankedEntriesByDuration(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationRow, error) {
	rows, err := q.db.Query(ctx, getRankedEntriesByDuration, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankedEntriesByDurationRow
	for rows.Next() {
		var i GetRankedEntriesByDurationRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.ValueNumber,
			&i.ValueDurationMs,
			&i.ValueText,
			&i.ManualRank,
			&i.Note,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankedEntriesByDurationDesc = `-- name: GetRankedEntriesByDurationDesc :many
SELECT
  e.id, e.list_id, e.user_id, e.value_number, e.value_duration_ms, e.value_text, e.manual_rank, e.note, e.submitted_at, e.updated_at,
  u.display_name,
  u.avatar_url,
  ROW_NUMBER() OVER (ORDER BY e.value_duration_ms DESC NULLS LAST) AS rank
FROM entries e
JOIN users u ON u.id = e.user_id
WHERE e.list_id = $1
ORDER BY rank ASC
`

type GetRankedEntriesByDurationDescRow struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Rank            int64              `json:"rank"`
}

func (q *Queries) GetRankedEntriesByDurationDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationDescRow, error) {
	rows, err := q.db.Query(ctx, getRankedEntriesByDurationDesc, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankedEntriesByDurationDescRow
	for rows.Next() {
		var i GetRankedEntriesByDurationDescRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.ValueNumber,
			&i.ValueDurationMs,
			&i.ValueText,
			&i.ManualRank,
			&i.Note,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankedEntriesByNumber = `-- name: GetRankedEntriesByNumber :many
SELECT
  e.id, e.list_id, e.user_id, e.value_number, e.value_duration_ms, e.value_text, e.manual_rank, e.note, e.submitted_at, e.updated_at,
  u.display_name,
  u.avatar_url,
  ROW_NUMBER() OVER (ORDER BY e.value_number ASC NULLS LAST) AS rank
FROM entries e
JOIN users u ON u.id = e.user_id
WHERE e.list_id = $1
ORDER BY rank ASC
`

type GetRankedEntriesByNumberRow struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Rank            int64              `json:"rank"`
}

func (q *Queries) GetRankedEntriesByNumber(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberRow, error) {
	rows, err := q.db.Query(ctx, getRankedEntriesByNumber, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankedEntriesByNumberRow
	for rows.Next() {
		var i GetRankedEntriesByNumberRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.ValueNumber,
			&i.ValueDurationMs,
			&i.ValueText,
			&i.ManualRank,
			&i.Note,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankedEntriesByNumberDesc = `-- name: GetRankedEntriesByNumberDesc :many
SELECT
  e.id, e.list_id, e.user_id, e.value_number, e.value_duration_ms, e.value_text, e.manual_rank, e.note, e.submitted_at, e.updated_at,
  u.display_name,
  u.avatar_url,
  ROW_NUMBER() OVER (ORDER BY e.value_number DESC NULLS LAST) AS rank
FROM entries e
JOIN users u ON u.id = e.user_id
WHERE e.list_id = $1
ORDER BY rank ASC
`

type GetRankedEntriesByNumberDescRow struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Rank            int64              `json:"rank"`
}

func (q *Queries) GetRankedEntriesByNumberDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberDescRow, error) {
	rows, err := q.db.Query(ctx, getRankedEntriesByNumberDesc, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankedEntriesByNumberDescRow
	for rows.Next() {
		var i GetRankedEntriesByNumberDescRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.ValueNumber,
			&i.ValueDurationMs,
			&i.ValueText,
			&i.ManualRank,
			&i.Note,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankedEntriesByText = `-- name: GetRankedEntriesByText :many
SELECT
  e.id, e.list_id, e.user_id, e.value_number, e.value_duration_ms, e.value_text, e.manual_rank, e.note, e.submitted_at, e.updated_at,
  u.display_name,
  u.avatar_url,
  ROW_NUMBER() OVER (ORDER BY e.manual_rank ASC NULLS LAST) AS rank
FROM entries e
JOIN users u ON u.id = e.user_id
WHERE e.list_id = $1
ORDER BY rank ASC
`

type GetRankedEntriesByTextRow struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Rank            int64              `json:"rank"`
}

func (q *Queries) GetRankedEntriesByText(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByTextRow, error) {
	rows, err := q.db.Query(ctx, getRankedEntriesByText, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankedEntriesByTextRow
	for rows.Next() {
		var i GetRankedEntriesByTextRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.ValueNumber,
			&i.ValueDurationMs,
			&i.ValueText,
			&i.ManualRank,
			&i.Note,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryManualRank = `-- name: UpdateEntryManualRank :exec
UPDATE entries SET manual_rank = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEntryManualRankParams struct {
	ID         pgtype.UUID `json:"id"`
	ManualRank pgtype.Int4 `json:"manual_rank"`
}

func (q *Queries) UpdateEntryManualRank(ctx context.Context, arg UpdateEntryManualRankParams) error {
	_, err := q.db.Exec(ctx, updateEntryManualRank, arg.ID, arg.ManualRank)
	return err
}

const upsertEntry = `-- name: UpsertEntry :one
INSERT INTO entries (list_id, user_id, value_number, value_duration_ms, value_text, note, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (list_id, user_id)
DO UPDATE SET
  value_number      = EXCLUDED.value_number,
  value_duration_ms = EXCLUDED.value_duration_ms,
  value_text        = EXCLUDED.value_text,
  note              = EXCLUDED.note,
  updated_at        = NOW()
RETURNING id, list_id, user_id, value_number, value_duration_ms, value_text, manual_rank, note, submitted_at, updated_at
`

type UpsertEntryParams struct {
	ListID          pgtype.UUID   `json:"list_id"`
	UserID          pgtype.UUID   `json:"user_id"`
	ValueNumber     pgtype.Float8 `json:"value_number"`
	ValueDurationMs pgtype.Int8   `json:"value_duration_ms"`
	ValueText       pgtype.Text   `json:"value_text"`
	Note            pgtype.Text   `json:"note"`
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, upsertEntry,
		arg.ListID,
		arg.UserID,
		arg.ValueNumber,
		arg.ValueDurationMs,
		arg.ValueText,
		arg.Note,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.UserID,
		&i.ValueNumber,
		&i.ValueDurationMs,
		&i.ValueText,
		&i.ManualRank,
		&i.Note,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}
