// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListMember = `-- name: CreateListMember :one
INSERT INTO list_members (list_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING list_id, user_id, role, joined_at
`

type CreateListMemberParams struct {
	ListID pgtype.UUID `json:"list_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) CreateListMember(ctx context.Context, arg CreateListMemberParams) (ListMember, error) {
	row := q.db.QueryRow(ctx, createListMember, arg.ListID, arg.UserID, arg.Role)
	var i ListMember
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteListMember = `-- name: DeleteListMember :exec
DELETE FROM list_members WHERE list_id = $1 AND user_id = $2
`

type DeleteListMemberParams struct {
	ListID pgtype.UUID `json:"list_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteListMember(ctx context.Context, arg DeleteListMemberParams) error {
	_, err := q.db.Exec(ctx, deleteListMember, arg.ListID, arg.UserID)
	return err
}

const getListMember = `-- name: GetListMember :one
SELECT list_id, user_id, role, joined_at FROM list_members WHERE list_id = $1 AND user_id = $2
`

type GetListMemberParams struct {
	ListID pgtype.UUID `json:"list_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error) {
	row := q.db.QueryRow(ctx, getListMember, arg.ListID, arg.UserID)
	var i ListMember
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT lm.list_id, lm.user_id, lm.role, lm.joined_at, u.display_name, u.avatar_url
FROM list_members lm
JOIN users u ON u.id = lm.user_id
WHERE lm.list_id = $1
ORDER BY lm.joined_at ASC
`

type ListMembersRow struct {
	ListID      pgtype.UUID        `json:"list_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListMembers(ctx context.Context, listID pgtype.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ListID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE list_members SET role = $3
WHERE list_id = $1 AND user_id = $2
RETURNING list_id, user_id, role, joined_at
`

type UpdateMemberRoleParams struct {
	ListID pgtype.UUID `json:"list_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (ListMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.ListID, arg.UserID, arg.Role)
	var i ListMember
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
