// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (owner_id, title, description, value_type, rank_order, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, title, description, value_type, rank_order, is_public, invite_token, created_at, updated_at
`

type CreateListParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	ValueType   string      `json:"value_type"`
	RankOrder   string      `json:"rank_order"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.ValueType,
		arg.RankOrder,
		arg.IsPublic,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.ValueType,
		&i.RankOrder,
		&i.IsPublic,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getInvitePreview = `-- name: GetInvitePreview :one
SELECT
  l.id,
  l.title,
  l.value_type,
  l.is_public,
  (SELECT COUNT(*) FROM list_members WHERE list_id = l.id) AS member_count
FROM lists l
WHERE l.invite_token = $1
`

type GetInvitePreviewRow struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	ValueType   string      `json:"value_type"`
	IsPublic    bool        `json:"is_public"`
	MemberCount int64       `json:"member_count"`
}

func (q *Queries) GetInvitePreview(ctx context.Context, inviteToken pgtype.UUID) (GetInvitePreviewRow, error) {
	row := q.db.QueryRow(ctx, getInvitePreview, inviteToken)
	var i GetInvitePreviewRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ValueType,
		&i.IsPublic,
		&i.MemberCount,
	)
	return i, err
}

const getListByID = `-- name: GetListByID :one
SELECT id, owner_id, title, description, value_type, rank_order, is_public, invite_token, created_at, updated_at FROM lists WHERE id = $1
`

func (q *Queries) GetListByID(ctx context.Context, id pgtype.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.ValueType,
		&i.RankOrder,
		&i.IsPublic,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListByInviteToken = `-- name: GetListByInviteToken :one
SELECT id, owner_id, title, description, value_type, rank_order, is_public, invite_token, created_at, updated_at FROM lists WHERE invite_token = $1
`

func (q *Queries) GetListByInviteToken(ctx context.Context, inviteToken pgtype.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getListByInviteToken, inviteToken)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.ValueType,
		&i.RankOrder,
		&i.IsPublic,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLists = `-- name: GetUserLists :many
SELECT
  l.id, l.owner_id, l.title, l.description, l.value_type, l.rank_order, l.is_public, l.invite_token, l.created_at, l.updated_at,
  lm.role AS user_role,
  e.id AS own_entry_id,
  e.value_number AS own_entry_value_number,
  e.value_duration_ms AS own_entry_value_duration_ms,
  e.value_text AS own_entry_value_text,
  e.manual_rank AS own_entry_manual_rank
FROM lists l
JOIN list_members lm ON lm.list_id = l.id AND lm.user_id = $1
LEFT JOIN entries e ON e.list_id = l.id AND e.user_id = $1
ORDER BY l.updated_at DESC
`

type GetUserListsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OwnerID                 pgtype.UUID        `json:"owner_id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	ValueType               string             `json:"value_type"`
	RankOrder               string             `json:"rank_order"`
	IsPublic                bool               `json:"is_public"`
	InviteToken             pgtype.UUID        `json:"invite_token"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UserRole                string             `json:"user_role"`
	OwnEntryID              pgtype.UUID        `json:"own_entry_id"`
	OwnEntryValueNumber     pgtype.Float8      `json:"own_entry_value_number"`
	OwnEntryValueDurationMs pgtype.Int8        `json:"own_entry_value_duration_ms"`
	OwnEntryValueText       pgtype.Text        `json:"own_entry_value_text"`
	OwnEntryManualRank      pgtype.Int4        `json:"own_entry_manual_rank"`
}

func (q *Queries) GetUserLists(ctx context.Context, userID pgtype.UUID) ([]GetUserListsRow, error) {
	rows, err := q.db.Query(ctx, getUserLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListsRow
	for rows.Next() {
		var i GetUserListsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.ValueType,
			&i.RankOrder,
			&i.IsPublic,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserRole,
			&i.OwnEntryID,
			&i.OwnEntryValueNumber,
			&i.OwnEntryValueDurationMs,
			&i.OwnEntryValueText,
			&i.OwnEntryManualRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET title = $2, description = $3, is_public = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, value_type, rank_order, is_public, invite_token, created_at, updated_at
`

type UpdateListParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsPublic,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.ValueType,
		&i.RankOrder,
		&i.IsPublic,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
