// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entry struct {
	ID              pgtype.UUID        `json:"id"`
	ListID          pgtype.UUID        `json:"list_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ValueNumber     pgtype.Float8      `json:"value_number"`
	ValueDurationMs pgtype.Int8        `json:"value_duration_ms"`
	ValueText       pgtype.Text        `json:"value_text"`
	ManualRank      pgtype.Int4        `json:"manual_rank"`
	Note            pgtype.Text        `json:"note"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type List struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ValueType   string             `json:"value_type"`
	RankOrder   string             `json:"rank_order"`
	IsPublic    bool               `json:"is_public"`
	InviteToken pgtype.UUID        `json:"invite_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ListMember struct {
	ListID   pgtype.UUID        `json:"list_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	AuthProvider string             `json:"auth_provider"`
	AppleSub     pgtype.Text        `json:"apple_sub"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
