// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAppleUser(ctx context.Context, arg CreateAppleUserParams) (User, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListMember(ctx context.Context, arg CreateListMemberParams) (ListMember, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEntry(ctx context.Context, id pgtype.UUID) error
	DeleteEntryByListAndUser(ctx context.Context, arg DeleteEntryByListAndUserParams) error
	DeleteList(ctx context.Context, id pgtype.UUID) error
	DeleteListMember(ctx context.Context, arg DeleteListMemberParams) error
	GetInvitePreview(ctx context.Context, inviteToken pgtype.UUID) (GetInvitePreviewRow, error)
	GetListByID(ctx context.Context, id pgtype.UUID) (List, error)
	GetListByInviteToken(ctx context.Context, inviteToken pgtype.UUID) (List, error)
	GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error)
	GetRankedEntriesByDuration(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationRow, error)
	GetRankedEntriesByDurationDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationDescRow, error)
	GetRankedEntriesByNumber(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberRow, error)
	GetRankedEntriesByNumberDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberDescRow, error)
	GetRankedEntriesByText(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByTextRow, error)
	GetUserByAppleSub(ctx context.Context, appleSub pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserLists(ctx context.Context, userID pgtype.UUID) ([]GetUserListsRow, error)
	GetValidRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	ListMembers(ctx context.Context, listID pgtype.UUID) ([]ListMembersRow, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error)
	UpdateEntryManualRank(ctx context.Context, arg UpdateEntryManualRankParams) error
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (ListMember, error)
	UpsertEntry(ctx context.Context, arg UpsertEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
