// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveEntry(ctx context.Context, arg ApproveEntryParams) error
	CreateAppleUser(ctx context.Context, arg CreateAppleUserParams) (User, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateListMember(ctx context.Context, arg CreateListMemberParams) (ListMember, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEntry(ctx context.Context, id pgtype.UUID) error
	DeleteEntryByListAndUser(ctx context.Context, arg DeleteEntryByListAndUserParams) error
	DeleteList(ctx context.Context, id pgtype.UUID) error
	DeleteListMember(ctx context.Context, arg DeleteListMemberParams) error
	// DeleteUser cascades through every FK in 001_init.sql:
	//   refresh_tokens (user_id), entries (user_id), list_members (user_id),
	//   lists (owner_id). A user pressing "Delete account" therefore also
	//   wipes any board they own — known limitation, see README.
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCurrentRankByDuration(ctx context.Context, arg GetCurrentRankByDurationParams) (int32, error)
	GetCurrentRankByDurationDesc(ctx context.Context, arg GetCurrentRankByDurationDescParams) (int32, error)
	// ── current rank lookups (used to populate previous_rank on upsert) ──
	GetCurrentRankByNumber(ctx context.Context, arg GetCurrentRankByNumberParams) (int32, error)
	GetCurrentRankByNumberDesc(ctx context.Context, arg GetCurrentRankByNumberDescParams) (int32, error)
	GetCurrentRankByText(ctx context.Context, arg GetCurrentRankByTextParams) (int32, error)
	GetEntryByListAndUser(ctx context.Context, arg GetEntryByListAndUserParams) (Entry, error)
	GetInvitePreview(ctx context.Context, inviteToken pgtype.UUID) (GetInvitePreviewRow, error)
	GetListByID(ctx context.Context, id pgtype.UUID) (List, error)
	GetListByInviteToken(ctx context.Context, inviteToken pgtype.UUID) (List, error)
	GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error)
	// ── moderation feed ──────────────────────────────────────────────────
	GetPendingEntries(ctx context.Context, listID pgtype.UUID) ([]GetPendingEntriesRow, error)
	GetPublicBoardsForUser(ctx context.Context, userID pgtype.UUID) ([]GetPublicBoardsForUserRow, error)
	GetRankedEntriesByDuration(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationRow, error)
	GetRankedEntriesByDurationDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByDurationDescRow, error)
	// ── ranked feeds (only "approved" entries are ranked) ────────────────
	GetRankedEntriesByNumber(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberRow, error)
	GetRankedEntriesByNumberDesc(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByNumberDescRow, error)
	GetRankedEntriesByText(ctx context.Context, listID pgtype.UUID) ([]GetRankedEntriesByTextRow, error)
	// GetRefreshTokenAny finds a refresh token by value regardless of
	// revoked / expired state. Used by the reuse-detection path: if a
	// caller presents an already-revoked token, that's a strong signal of
	// token theft, and we revoke every refresh token for that user.
	GetRefreshTokenAny(ctx context.Context, token string) (RefreshToken, error)
	GetUserByAppleSub(ctx context.Context, appleSub pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// GetUserLists returns one row per list the caller belongs to, including
	// their current rank if they have an entry. The rank is computed
	// in-line as `count_of_better + 1` to avoid an N+1 round-trip (one rank
	// query per board) from the handler — a single SELECT now drives the
	// entire home feed.
	//
	// The CASE chain dispatches on the list's value_type / rank_order:
	//   - number   asc : lower value wins
	//   - number   desc: higher value wins
	//   - duration asc : faster wins
	//   - duration desc: slower wins
	//   - text         : manual_rank wins (lower is better)
	// We treat the user as unranked (NULL own_rank) when their entry doesn't
	// exist OR is not approved.
	GetUserLists(ctx context.Context, userID pgtype.UUID) ([]GetUserListsRow, error)
	GetUserProfile(ctx context.Context, id pgtype.UUID) (GetUserProfileRow, error)
	GetValidRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	ListMembers(ctx context.Context, listID pgtype.UUID) ([]ListMembersRow, error)
	RegenerateInviteToken(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	RejectEntry(ctx context.Context, arg RejectEntryParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SearchPublicLists(ctx context.Context, arg SearchPublicListsParams) ([]SearchPublicListsRow, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error)
	UpdateEntryManualRank(ctx context.Context, arg UpdateEntryManualRankParams) error
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (ListMember, error)
	UpsertEntry(ctx context.Context, arg UpsertEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
