// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppleUser = `-- name: CreateAppleUser :one
INSERT INTO users (email, display_name, auth_provider, apple_sub)
VALUES ($1, $2, 'apple', $3)
RETURNING id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at
`

type CreateAppleUserParams struct {
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AppleSub    pgtype.Text `json:"apple_sub"`
}

func (q *Queries) CreateAppleUser(ctx context.Context, arg CreateAppleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAppleUser, arg.Email, arg.DisplayName, arg.AppleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, auth_provider, password_hash)
VALUES ($1, $2, 'email', $3)
RETURNING id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAppleSub = `-- name: GetUserByAppleSub :one
SELECT id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at FROM users WHERE apple_sub = $1
`

func (q *Queries) GetUserByAppleSub(ctx context.Context, appleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleSub, appleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users SET display_name = $2 WHERE id = $1
RETURNING id, email, display_name, auth_provider, apple_sub, password_hash, avatar_url, created_at
`

type UpdateDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AuthProvider,
		&i.AppleSub,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
